export const KNOWN_ACTION_MENU_PRESETS = ["languages"] as const;

export const SKILL_TAG_CATEGORIES = {
  research: "Reading & Research",
  writing: "Writing & Communication",
  shopping: "Shopping & Commerce",
  code: "Coding & Development",
  learning: "Learning & Tutoring",
  language: "Languages & Translation",
  content: "Social & Content",
  data: "Data & Analytics",
  automation: "Browser & Workflow Automation",
  marketing: "Marketing & Sales",
  productivity: "Productivity",
  finance: "Finance",
} as const;

export const KNOWN_SKILL_TAGS = Object.keys(SKILL_TAG_CATEGORIES) as Array<
  keyof typeof SKILL_TAG_CATEGORIES
>;

export const KNOWN_SKILL_ICONS = [
  "Activity",
  "BadgePercent",
  "BedDouble",
  "Bell",
  "BicepsFlexed",
  "BookMarked",
  "BookOpen",
  "Box",
  "Briefcase",
  "Calculator",
  "Calendar",
  "ChartNoAxesCombined",
  "Check",
  "CheckCheck",
  "Code",
  "Crown",
  "Earth",
  "FileText",
  "Flag",
  "GraduationCap",
  "Heart",
  "Highlighter",
  "House",
  "Languages",
  "Leaf",
  "Library",
  "Lightbulb",
  "List",
  "ListMinus",
  "ListPlus",
  "Mail",
  "Map",
  "MessageCircle",
  "MessageCircleQuestion",
  "MessageCircleReply",
  "Music",
  "Notebook",
  "PartyPopper",
  "Pencil",
  "PencilLine",
  "Plane",
  "Popcorn",
  "Repeat",
  "Salad",
  "ScrollText",
  "Search",
  "ShoppingBag",
  "ShoppingCart",
  "Sigma",
  "Sparkles",
  "Speech",
  "SpellCheck",
  "Star",
  "Table2",
  "Target",
  "TextQuote",
  "TextSearch",
  "Timer",
  "WandSparkles",
  "Zap",
] as const;
