export const KNOWN_ACTION_MENU_PRESETS = ["languages"] as const;

export const KNOWN_PROMPT_ICONS = [
  "Sparkles",
  "Pencil",
  "PencilLine",
  "Highlighter",
  "Wand",
  "WandSparkles",
  "Lightbulb",
  "Code",
  "FileText",
  "ScrollText",
  "Library",
  "ChartNoAxesCombined",
  "ShoppingBag",
  "Search",
  "TextSearch",
  "List",
  "ListMinus",
  "ListPlus",
  "MessageCircle",
  "MessageCircleQuestion",
  "MessageSquareReply",
  "Check",
  "CheckCheck",
  "Repeat",
  "Calendar",
  "BookOpen",
  "BookMarked",
  "Languages",
  "Zap",
  "Music",
  "Timer",
  "Calculator",
  "Briefcase",
  "Flag",
  "Heart",
  "Star",
  "Crown",
  "Sigma",
  "Target",
  "GraduationCap",
] as const;

export const DEFAULT_SOURCE_BRANCH = "main";
